version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - SIkebe
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - SIkebe
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: adoptopenjdk
    versions:
    - ">= 12.pre.jre.pre.hotspot.a, < 13"
  - dependency-name: adoptopenjdk
    versions:
    - ">= 13.pre.jre.pre.hotspot.a, < 14"
  - dependency-name: adoptopenjdk
    versions:
    - ">= 14.pre.jre.pre.hotspot.a, < 15"
