# Build script
image: Visual Studio 2017
init:
  - git config --global core.autocrlf true
install:
  - choco install docker-compose
# Build script
build_script:
  - ps: docker version
  - ps: docker-compose version
  - ps: .\build.ps1 --target="Run-All-Tests"

# Tests
test: off

# Branches to build
branches:
  # Whitelist
  only:
    - develop
    - main
    - /r/.*/
    - /release/.*/
    - /hotfix/.*/
    - /feature/.*/

# Build cache
cache:
- tools -> build.cake, build.config