version: '3'

services:
  gitbucket:
    image: gitbucket/gitbucket
    restart: always
    ports:
      - 8080:8080
    #volumes:
    #  - ./gitbucket:/gitbucket
    depends_on:
      - db
    environment:
      - GITBUCKET_DB_URL=jdbc:postgresql://db/gitbucket
      - GITBUCKET_DB_USER=gitbucket
      - GITBUCKET_DB_PASSWORD=gitbucket
      - GITBUCKET_BASE_URL=http://localhost:8080
    #  - GITBUCKET_HOME=./gitbucket
    #entrypoint: ./wait-for-it.sh db:3306
    command: ["sh", "-c", "java -jar /opt/gitbucket.war"]
    #command: ./wait-for-it.sh db gitbucket gitbucket sh -c java -jar /opt/gitbucket.war

  db:
    image: postgres:11.4-alpine
    restart: always
    ports:
      - "3306:5432"
    environment:
      - POSTGRES_DB=gitbucket
      - POSTGRES_USER=gitbucket
      - POSTGRES_PASSWORD=gitbucket