<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NoWarn>CA2227</NoWarn>
    <ImplicitUsings>false</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" >
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>

</Project>
