name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - develop

jobs:
  linux-e2e:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Install PostgreSQL
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install postgresql-15
        shell: bash
      - name: Build and Run E2E Tests On Linux
        run: .\build.ps1 --target Run-E2E-Tests
        shell: pwsh

  linux-e2e-scd:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Install PostgreSQL
        run: |
          sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
          curl https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
          sudo apt-get update
          sudo apt-get install postgresql-14
        shell: bash
      - name: Build and Run E2E Tests Using SingleFileExe On Linux
        run: .\build.ps1 --target Run-E2E-Tests-Using-SingleFileExe --rid linux-x64
        shell: pwsh

  windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Build and Run Unit Tests On Windows
        run: .\build.ps1 --target Run-Unit-Tests
        shell: powershell

  macOS:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Build and Run Unit Tests On macOS
        run: .\build.ps1 --target Run-Unit-Tests
        shell: pwsh
