name: Build and Run Unit Tests

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Run Unit Tests
      run: .\build.ps1 -target=Run-Unit-Tests
      shell: powershell