name: Build and Run Unit Tests

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Build and Run Unit Tests Linux
        run: dotnet test src/GitBucket.Service.Tests/GitBucket.Service.Tests.csproj
        shell: bash

  windows:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - name: Build and Run Unit Tests On Windows
        run: .\build.ps1 target=Run-Unit-Tests
        shell: powershell
