on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Verify commit exists in origin/master
      run: |
        git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
        git branch --remote --contains | grep origin/master

    - name: Pack
      run: dotnet pack ./src/GbUtil/GbUtil.csproj -c Release -o ./packages

    - name: Push
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: dotnet nuget push ./packages/GbUtil.0.14.0.nupkg -k ${{ env.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
